# Generated by Django 2.2.1 on 2019-09-18 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190918_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 18, 17, 29, 11, 264313, tzinfo=utc)),
        ),
    ]
